name: $(Build.DefinitionName).$(Build.SourceBranchName).$(Date:yyyyMMdd).$(Rev:r)

pool: 'Hyrule'

pr:
- develop
- main

trigger:
- develop
- main

stages:
  - stage: Build_Pandora
    displayName: 'Build Pandora'
    jobs:
      - job: Build
        displayName: 'Build'
        variables:
          buildConfiguration: '--configuration Release'
          projectsPath: '**/*.csproj'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Restore packages'
            inputs:
              command: restore
              projects: $(projectsPath)
              feedsToUse: 'select'
              vstsFeed: '1ef4c0cf-1819-4ee1-8807-d43cd89c12fe/ddbe434d-9f4f-404b-8ac2-fd37fda6529e'
          - task: DotNetCoreCLI@2
            displayName: 'Compile all projects'
            inputs:
              command: build
              projects: $(projectsPath)
              arguments: '$(buildConfiguration)'
          - task: DotNetCoreCLI@2
            displayName: 'Run unit tests'
            inputs:
              command: test
              projects: '**/*.Tests.csproj'
              arguments: '$(buildConfiguration)'